In [1]:
import numpy as np

In [49]:
base = np.zeros((3, 3))
base

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# base[1,1] = 1
# base

In [35]:
# for i in range(가로):
#     for j in range(세로):
#         print(i, j)

In [66]:
좌상단꼭지점 = (3, 3)
사이즈 = (3, 4)

base_arr = np.zeros((10, 10))

x, y = 좌상단꼭지점
x = max(x - 1, 0)
y = max(y - 1, 0)

for i in range(사이즈[0]):
    for j in range(사이즈[1]):
        # print(i+좌상단꼭지점[0], j+좌상단꼭지점[1])
        base_arr[i+y, j+x] = 1
base_arr     

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
def 블록배치레이아웃(정반사이즈, 좌상단꼭지점좌표, 블록사이즈, blk_id):
    정반어레이 = np.zeros((정반사이즈[0], 정반사이즈[1]))
    x, y = 좌상단꼭지점
    x = max(x - 1, 0)
    y = max(y - 1, 0)
    for i in range(블록사이즈[0]):
        for j in range(블록사이즈[1]):
            정반어레이[i+x,j+y] = blk_id   
    return 정반어레이   

In [69]:
정반어레이 = 블록배치레이아웃((10, 10), (2, 1), (5, 3), 1)
정반어레이

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])